# frozen_string_literal: true

source 'https://rubygems.org'

ruby '~> 3.2'

gem 'dotenv', '~> 3.1'
gem 'pg', '~> 1.6'
gem 'puma', '~> 6.6'
gem 'rack', '~> 3.1'
gem 'rackup', '~> 2.2'
gem 'sinatra', '~> 4.1'

group :development do
  gem 'rerun', '~> 0.14'
end
